### ISSUE TITLE
kcd observe with non-updated helm repo prints stack strace

### ISSUE THREAD

**Issue by morimekta** [kubecd/kubecd#14]
```
$ kcd observe --image us.gcr.io/my-project/my-service:abcdef0 --patch
Error: failed to download "stable/redis-ha"
Traceback (most recent call last):
  File "/home/steineldar/.local/bin/kcd", line 11, in <module>
    sys.exit(main())
  File "/home/steineldar/.local/lib/python3.6/site-packages/kubecd/cli/__init__.py", line 175, in main
    func(**kwargs)
  File "/home/steineldar/.local/lib/python3.6/site-packages/kubecd/cli/commands.py", line 120, in observe_new_image
    image_index = kcd_config.image_index
  File "/home/steineldar/.local/lib/python3.6/site-packages/kubecd/model.py", line 194, in image_index
    values = helm.get_resolved_values(rel, env, skip_value_from=True)
  File "/home/steineldar/.local/lib/python3.6/site-packages/kubecd/helm.py", line 224, in get_resolved_values
    output = inspect(release.chart.reference, release.chart.version)
  File "/home/steineldar/.local/lib/python3.6/site-packages/kubecd/helm.py", line 20, in inspect
    output = subprocess.check_output(cmd).decode('utf-8').split("\n---\n")[1]
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['helm', 'inspect', 'stable/redis-ha', '--version', '2.2.3']' returned non-zero exit status 1.
```

Should print shorter error and suggest to update helm.

**Comment by stigsb** [comment]
Closing all Python-related issues.
