### ISSUE TITLE
kcd diff does not work

### ISSUE THREAD

**Issue by morimekta** [kubecd/kubecd#7]
```
$ kcd diff
Traceback (most recent call last):
  File "/home/steineldar/.local/bin/kcd", line 11, in <module>
    sys.exit(main())
  File "/home/steineldar/.local/venvs/kubecd/lib/python3.6/site-packages/kubecd/cli/__init__.py", line 291, in main
    func(**kwargs)
  File "/home/steineldar/.local/venvs/kubecd/lib/python3.6/site-packages/kubecd/cli/__init__.py", line 93, in diff_release
    e = kcd_config.env_by_name(env)
  File "/home/steineldar/.local/venvs/kubecd/lib/python3.6/site-packages/kubecd/model.py", line 142, in env_by_name
    return self._env_index[name]
KeyError: None
```

**Comment by stigsb** [comment]
Not done yet :) . Keeping issue open as a feature request.
